// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiN75sHjs2IrOlZexXNVIx0jUnq2IKZW8',
    appId: '1:760211071103:web:81b8f5d2fffc033a385f4a',
    messagingSenderId: '760211071103',
    projectId: 'chatopia-f51d0',
    authDomain: 'chatopia-f51d0.firebaseapp.com',
    storageBucket: 'chatopia-f51d0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3WsiGip_lTO2md-UIgfZ-CggdqzRlLnQ',
    appId: '1:760211071103:android:fe6a7e203a0851eb385f4a',
    messagingSenderId: '760211071103',
    projectId: 'chatopia-f51d0',
    storageBucket: 'chatopia-f51d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB8p6mHy6PcUjDvSj_OEY4o-AOget8314',
    appId: '1:760211071103:ios:2a99d21a0b467e54385f4a',
    messagingSenderId: '760211071103',
    projectId: 'chatopia-f51d0',
    storageBucket: 'chatopia-f51d0.appspot.com',
    iosClientId: '760211071103-dug4tcb3g5qb6j07q996j629v33ltp8s.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatopia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAB8p6mHy6PcUjDvSj_OEY4o-AOget8314',
    appId: '1:760211071103:ios:4f79a3f2e5313a4e385f4a',
    messagingSenderId: '760211071103',
    projectId: 'chatopia-f51d0',
    storageBucket: 'chatopia-f51d0.appspot.com',
    iosClientId: '760211071103-7jrcpirmit36hbm01ofl5cp38lk1t3ua.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatopia.RunnerTests',
  );
}
